In [151]:
import pandas as pd

In [152]:
#for now concentrating only on cities in Arizona
df=pd.read_csv('AZ_cities.txt', sep="\t", header=None, lineterminator=';')

In [153]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,064fFc4CdNxAJJDVR-7FSQ,Horton Carpet Cleaning,NaN,NaN,Ahwahtukee,AZ,85044.0,33.3427,-111.984,5.0,15,1
1,-v8Z3mdbbPs1ljLziHr2DA,My Wine Cellar,NaN,"5030 E Warner Rd, Ste 2",Ahwatukee,AZ,85044.0,33.3337,-111.978,4.0,176,1
2,0Rni7ocMC_Lg2UH0lDeKMQ,Barro's Pizza,NaN,4625 E Ray Rd,Ahwatukee,AZ,85044.0,33.3181,-111.984,3.5,74,1
3,ALvsc69ygqJfG5wLRryj-g,Sprinkler Detective,NaN,NaN,Ahwatukee,AZ,85044.0,33.3427,-111.984,4.5,5,1
4,FYWN1wneV18bWNgQjJ2GNg,Dental by Design,NaN,"4855 E Warner Rd, Ste B9",Ahwatukee,AZ,85044.0,33.3307,-111.979,4.0,22,1

In [154]:
len(df)

52214

In [155]:
def find_sum(l):
    return sum(l)

In [156]:
# AZ    | Phoenix    |    17213
# AZ    | Scottsdale |     8227
# AZ    | Mesa       |     5871 
# AZ    | Tempe      |     4263 

l=[17213, 8227, 5871, 4263]
find_sum(l)

35574

In [157]:
#assigning columns names
df.columns=['business_id', 'business_name', 'neighborhood','address','city', 'state','postal_code', 'latitude','longitude','stars', 'review_count', 'open']

In [158]:
df.head()

,business_id,business_name,neighborhood,address,city,state,postal_code,latitude,longitude,stars,review_count,open
0,064fFc4CdNxAJJDVR-7FSQ,Horton Carpet Cleaning,NaN,NaN,Ahwahtukee,AZ,85044.0,33.3427,-111.984,5.0,15,1
1,-v8Z3mdbbPs1ljLziHr2DA,My Wine Cellar,NaN,"5030 E Warner Rd, Ste 2",Ahwatukee,AZ,85044.0,33.3337,-111.978,4.0,176,1
2,0Rni7ocMC_Lg2UH0lDeKMQ,Barro's Pizza,NaN,4625 E Ray Rd,Ahwatukee,AZ,85044.0,33.3181,-111.984,3.5,74,1
3,ALvsc69ygqJfG5wLRryj-g,Sprinkler Detective,NaN,NaN,Ahwatukee,AZ,85044.0,33.3427,-111.984,4.5,5,1
4,FYWN1wneV18bWNgQjJ2GNg,Dental by Design,NaN,"4855 E Warner Rd, Ste B9",Ahwatukee,AZ,85044.0,33.3307,-111.979,4.0,22,1

In [159]:
df['city'].unique()

array(['Ahwahtukee', 'Ahwatukee', 'Ahwatukee Foothills Village', 'Anthem',
       'Arrowhead', 'Avondale', 'Canyon Village', 'Carefree',
       'Cave Creek', 'Central City', 'Central City Village', 'Chander',
       'Chandler', 'Chandler-Gilbert', 'Desert Ridge', 'East Mesa',
       'El Mirage', 'Estrella Village', 'Fort McDowell', 'Fountain Hills',
       'Fountain Hls', 'Gelndale', 'Gilbert', 'Gilbert AZ', 'Gillbert',
       'Glbert', 'Glendale', 'Glendale Az', 'Goodyear', 'Goodyear AZ',
       'Guadalupe', 'Henderson', 'Higley', 'Las Vegas', 'Laveen',
       'Laveen Village', 'Litchfield', 'Litchfield Park',
       'Maricopa County', 'Mesa', 'MESA', 'mesa', 'Mesa Arizona',
       'Mesa AZ', 'Meza', 'North Scottsdale', 'Old Scottsdale',
       'Old Town Scottsdale', 'Paradise Valley', 'Peoria', 'peoria',
       "Peoria Ave Citizen's Group", 'Pheonix', 'Pheonix AZ', 'Phoeniix',
       'Phoenix', 'Phoenix AZ', 'Phoenix metro area', 'Phoenix Valley',
       'Phoenix,', 'Phoenix, AZ', 'Phoneix', 'Phoniex', 'Phx',
       'Rainbow Valley', 'Roosevelt', 'San Tan', 'San Tan Valley',
       'Schottsdale', 'Scotesdale', 'Scottdale', 'Scottsdale',
       'Scottsdale, AZ', 'Stetson Valley', 'Sun City', 'Sun City Anthem',
       'Sun City West', 'Sun Lakes', 'Suncity', 'Sunnyslope',
       'Superstition Mountain', 'Suprise', 'Surprise',
       'Surprise Crossing', 'Tempe', 'The Promenade', 'The Woodlands',
       'Tolleson', 'Waddell', 'Westworld Scottsdale', 'Youngtown'],
      dtype=object)

In [160]:
#As can be seen this is not an effective method at all. I have replaced the ciy names manually. This is a case in point where NLP techniques can be deployed to group similar names together or even could try NMF or K-means clustering to group similar names together - but not sure how effective K-means could be
df.loc[:, 'city'].replace(['Ahwahtukee','Ahwatukee Foothills Village','Central City Village', 'Chander', 'Chandler-Gilbert','Fountain Hls', 'Gelndale', 'Gilbert AZ', 'Gillbert', 'Glbert', 'Glendale Az', 'Goodyear AZ', 'Laveen Village', 'Litchfield Park', 'MESA', 'mesa','Mesa Arizona', 'Mesa AZ', 'Meza', 'Old Town Scottsdale', 'peoria', "Peoria Ave Citizen's Group",'Pheonix','Pheonix AZ', 'Phoeniix', 'Phoenix', 'Phoenix AZ','Phoenix metro area', 'Phoenix Valley', 'Phoenix,', 'Phoenix, AZ','Phoneix', 'Phoniex', 'Phx', 'San Tan Valley', 'Schottsdale', 'Scotesdale', 'Scottdale', 'Scottsdale, AZ', 'Sun City Anthem', 'Sun City West', 'Sun Lakes','Suncity', 'Suprise', 'Surprise Crossing', 'Westworld Scottsdale'], ['Ahwatukee','Ahwatukee','Central City', 'Chandler', 'Chandler', 'Fountain Hills', 'Glendale', 'Gilbert', 'Gilbert','Gilbert','Glendale', 'Goodyear', 'Laveen', 'Litchfield', 'Mesa', 'Mesa', 'Mesa', 'Mesa', 'Mesa', 'Old Scottsdale', 'Peoria', 'Peoria', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix','Phoenix','Phoenix','Phoenix','Phoenix','Phoenix','Phoenix','Phoenix','Phoenix', 'San Tan', 'Scottsdale', 'Scottsdale','Scottsdale','Scottsdale', 'Sun City', 'Sun City', 'Sun City', 'Sun City', 'Surprise', 'Surprise', 'Scottsdale'], inplace=True)

In [161]:
df['city'].unique()

array(['Ahwatukee', 'Anthem', 'Arrowhead', 'Avondale', 'Canyon Village',
       'Carefree', 'Cave Creek', 'Central City', 'Chandler',
       'Desert Ridge', 'East Mesa', 'El Mirage', 'Estrella Village',
       'Fort McDowell', 'Fountain Hills', 'Glendale', 'Gilbert',
       'Goodyear', 'Guadalupe', 'Henderson', 'Higley', 'Las Vegas',
       'Laveen', 'Litchfield', 'Maricopa County', 'Mesa',
       'North Scottsdale', 'Old Scottsdale', 'Paradise Valley', 'Peoria',
       'Phoenix', 'Rainbow Valley', 'Roosevelt', 'San Tan', 'Scottsdale',
       'Stetson Valley', 'Sun City', 'Sunnyslope',
       'Superstition Mountain', 'Surprise', 'Tempe', 'The Promenade',
       'The Woodlands', 'Tolleson', 'Waddell', 'Youngtown'], dtype=object)

In [78]:
#df.loc[:, 'city'].replace(['Ahwahtukee', 'Ahwatukee Foothills Village'], ['Ahwatukee', 'Ahwatukee'], inplace=True)

In [162]:
#making city the index of the dataframe
df=df.set_index('city').sort_index(axis=0)

In [163]:
df.head()

,business_id,business_name,neighborhood,address,state,postal_code,latitude,longitude,stars,review_count,open
city,,,,,,,,,,,
Ahwatukee,064fFc4CdNxAJJDVR-7FSQ,Horton Carpet Cleaning,NaN,NaN,AZ,85044.0,33.3427,-111.984,5.0,15,1
Ahwatukee,qRuKEfk4Iqzm8TIu6PuN_w,Desert Foothills Trailhead,NaN,E Desert Foothills Pkwy,AZ,85048.0,33.3187,-112.068,5.0,9,1
Ahwatukee,sRAlmOAL7x8_o30-hXpdog,Healthy and Clean Living Environments,NaN,NaN,AZ,85048.0,33.3427,-111.984,4.5,4,1
Ahwatukee,qdCwzhJ5Yo_Sdm_bYDIfOQ,Kathy's Alterations,NaN,3902 E Chandler Blvd,AZ,85048.0,33.3055,-112.000,5.0,37,1
Ahwatukee,qJf61TR4Jq9Xph5RiXPS9A,Cupz N' Crepes,NaN,4232 E Chandler Blvd,AZ,85048.0,33.3053,-111.993,4.0,270,1

In [164]:
import numpy as np

In [120]:
np.deg2rad(-111.984)

-1.95448950955333

In [165]:
#to convert latitude form degrees to radians
df['latitude']=np.deg2rad(df['latitude'])

In [166]:
#to convert longitude form degrees to radians
df['longitude']=np.deg2rad(df['longitude'])

In [130]:
# #to round the values to 2 decimals
# df['latitude']=df['latitude']

In [131]:
# df['longitude']=df['longitude']

In [167]:
df1=df[['business_id', 'latitude', 'longitude']].groupby(level=0)

In [175]:
#to access the groups of grouped_by object 
city_det=[]
for city, group in df1:
    city_det.append(city)

In [ ]:
# if you print the group in df1 then you get the following outcome:
#     business_id  latitude  longitude


# city                                                  
# Ahwatukee  064fFc4CdNxAJJDVR-7FSQ  0.581940  -1.954490
# Ahwatukee  qRuKEfk4Iqzm8TIu6PuN_w  0.581521  -1.955956
# Ahwatukee  sRAlmOAL7x8_o30-hXpdog  0.581940  -1.954490
# Ahwatukee  qdCwzhJ5Yo_Sdm_bYDIfOQ  0.581291  -1.954769
# Ahwatukee  qJf61TR4Jq9Xph5RiXPS9A  0.581287  -1.954647
#                    business_id  latitude  longitude
# city                                               
# Anthem  bpYV3JbnymmqYk_Ov5aNXA  0.591078  -1.957334
# Anthem  cNwEKgWmNowNGZHbMlVrAw  0.590691  -1.956619
# Anthem  ePv_pnXUXuPf8h6Z4N1tmw  0.591045  -1.957247
# Anthem  jczUaabyGKOsRvQ7zTfj0Q  0.591120  -1.957195
# Anthem  fULZVqEt3qKFZjMw-ccOkQ  0.591056  -1.957195

In [169]:
#length of the dataframe after grouping_by
len(df1)

46

In [170]:
type(df1)

pandas.core.groupby.DataFrameGroupBy

In [141]:
#df1.head()

In [142]:
#use get_group to access each grouped_by value
#df1.get_group('Youngtown')

In [115]:
# define the number of miles in one radian
miles_per_radian = 3963.2

# approximate radius of earth in km
R = 6373.0

In [171]:
#To access the lats and longitude of every city, for now, in Arizona
def get_group(g, key):
    if key in g.groups: return g.get_group(key)
    return pd.DataFrame()

In [172]:
#you could access a specific group using get_group
get_group(df1, 'Glendale')

                     business_id  latitude  longitude
city
Glendale  fGblQa3PoNgRVG5HGaUhoQ  0.585294  -1.959324
Glendale  f6mQYyU_ga0DVRuRZhkmfQ  0.585275  -1.959342
Glendale  ewbQj7zVucaB_LJK3SlPtg  0.586621  -1.958033
Glendale  exbGwpAgfDEOKduO-G_enQ  0.585371  -1.957945
Glendale  eyy4s1k5hne3UC8cF_xwXw  0.587139  -1.957142
Glendale  ezh06vIIRSmCAkpLsu8SOw  0.585406  -1.959883
Glendale  f-v1fvtnbdw_QQRsCnwH-g  0.585296  -1.959324
Glendale  etuqjOrnTzoMY3kzk4s4FA  0.585373  -1.957998
Glendale  f59g8Ly0sYq1x-1MJji2ig  0.587357  -1.957701
Glendale  f97-G0ZWeLrIDyrS6xClxA  0.587521  -1.958033
Glendale  f8EDtDlaGuzrr0cpJTXwqg  0.587658  -1.958067
Glendale  f9152qrcOqmJyO_AnGm4nA  0.587092  -1.958259
Glendale  fFY974IAwd7U8RebrVDkVg  0.587518  -1.958050
Glendale  fAeMGaaWYvuPZVBF5nT9Bg  0.586101  -1.958050
Glendale  fB8ri0_dhcezdeTVYdRGkw  0.587106  -1.958766
Glendale  fCxwwGqTy0pNUGu7spnLgA  0.587387  -1.958225
Glendale  fDDNHVo29EPawGUDM7InUw  0.585361  -1.958015
Glendale  fEvDP0TeTGAwAh4r36O3xA  0.587879  -1.958347
Glendale  esMmw8jDyySv5Qke_KidXA  0.587516  -1.958033
Glendale  f7cWDVGUoIT1kZz_TyKhoQ  0.587680  -1.958015
Glendale  eriW9d0AXkQyLrX5W3p_Pw  0.586612  -1.958033
Glendale  eSkdZvn6Ij8PU8Ip5vtwVQ  0.588422  -1.958259
Glendale  enK5u-6zmHBmtd-cHJdIxQ  0.587516  -1.958033
Glendale  eREIn5_ufXNgKMrxFlYbiQ  0.587148  -1.957404
Glendale  eSENXDnnNSo-MLLkWJQ8Vg  0.585362  -1.958050
Glendale  eSTlwVZRmjO6rJ_MZ5KgjA  0.586652  -1.957928
Glendale  fHCf4N3K7Ul8TLj6z5CKFQ  0.586546  -1.957823
Glendale  eT8w06IjAJM-4xAEK3adzw  0.587103  -1.958067
Glendale  eVWUuhlsSd0EegXKaN1O4A  0.586373  -1.958277
Glendale  eaIQq4QuMhCnzAa3JyggEQ  0.585094  -1.958661
...                          ...       ...        ...
Glendale  KlxUAh9QUS1-8bFFqn9-fQ  0.587665  -1.958294
Glendale  Kninp4rnCwhtcTrpcuPJYQ  0.587659  -1.958050
Glendale  K5lajhnoiTXNSkFxjh2Etg  0.586619  -1.957631
Glendale  Kg-5o22CoWeDtr4Z45Rrag  0.587115  -1.958085
Glendale  KU8G1mu7BUImXQd8H4cg7w  0.588412  -1.958277
Glendale  KmjpEsorHeQEO6u4HGueDQ  0.585356  -1.958033
Glendale  KSHbL3GMhO3S4pPRgLVu4g  0.587122  -1.958713
Glendale  K7yZSZRgIaQXINc-BkA7HQ  0.587165  -1.958696
Glendale  KSM3RJ8EGHbQ0Id0LzFbkQ  0.587127  -1.958556
Glendale  K80anqDnRDkGWLWwgpTfag  0.585284  -1.959394
Glendale  K8VfVSmG1iOGGWQv17WlMA  0.585356  -1.957823
Glendale  KBTYT-YeCt5YZQULtXWbBA  0.587570  -1.958033
Glendale  KBxlctkFge-jGjMWQITaAQ  0.587597  -1.957736
Glendale  KE3jpynolXq36VmhH6Zn7w  0.587387  -1.958050
Glendale  KE75lY1iXnZiTxupxa04Hg  0.587202  -1.958713
Glendale  KEZOH8BJVJs52VMzSLkgFA  0.586881  -1.958050
Glendale  KEd-8p8Fb9m97h38awaP5g  0.585706  -1.958033
Glendale  KEwW5kX9MXmk-MV7EgDjgA  0.585698  -1.958312
Glendale  Kpmy4Pld2FbJixlJtEnP4w  0.587131  -1.958277
Glendale  KHdPQogdP6lil-P5Ka_s7A  0.587322  -1.958626
Glendale  KIgm2mYwVkEUmArgFHYoDg  0.588162  -1.957247
Glendale  KL0ja1DYvaP5AzgnYuADlA  0.586315  -1.957561
Glendale  KNXgGCluJMPyWM0i4xhZxw  0.588162  -1.957247
Glendale  KNzpIK7zrg_3yW6ErO5Wdg  0.585354  -1.958067
Glendale  KOIn7NNqmubBsycYeTwwVA  0.585347  -1.957683
Glendale  KGqvUQQA4c9GJpi5-znsew  0.588408  -1.957212
Glendale  KPfwWn0wcf482l_T9G6Q3g  0.587129  -1.958608
Glendale  KROUTYd3DSxcovaGg_bt3g  0.588042  -1.958591
Glendale  KQD9CN4sWz49yUp4Yt84mg  0.585596  -1.959272
Glendale  KRpJeRLhn9bs9gZ_e3-amg  0.585041  -1.959499

[3208 rows x 3 columns]

In [176]:
#list of city names
city_det

['Ahwatukee',
 'Anthem',
 'Arrowhead',
 'Avondale',
 'Canyon Village',
 'Carefree',
 'Cave Creek',
 'Central City',
 'Chandler',
 'Desert Ridge',
 'East Mesa',
 'El Mirage',
 'Estrella Village',
 'Fort McDowell',
 'Fountain Hills',
 'Gilbert',
 'Glendale',
 'Goodyear',
 'Guadalupe',
 'Henderson',
 'Higley',
 'Las Vegas',
 'Laveen',
 'Litchfield',
 'Maricopa County',
 'Mesa',
 'North Scottsdale',
 'Old Scottsdale',
 'Paradise Valley',
 'Peoria',
 'Phoenix',
 'Rainbow Valley',
 'Roosevelt',
 'San Tan',
 'Scottsdale',
 'Stetson Valley',
 'Sun City',
 'Sunnyslope',
 'Superstition Mountain',
 'Surprise',
 'Tempe',
 'The Promenade',
 'The Woodlands',
 'Tolleson',
 'Waddell',
 'Youngtown']

In [178]:
#the idea is to get the clusters for every city. So for every city name in the list I have to get the algorithm to find clusters
#and also have to link the clusters to appropriate business_id and city
def get_group(g, l):
    for key in l:
        if key in g.groups: return g.get_group(key)#when return appears the program execution stops immediately
    return pd.DataFrame()

In [179]:
get_group(df1, city_det)

                      business_id  latitude  longitude
city
Ahwatukee  064fFc4CdNxAJJDVR-7FSQ  0.581940  -1.954490
Ahwatukee  qRuKEfk4Iqzm8TIu6PuN_w  0.581521  -1.955956
Ahwatukee  sRAlmOAL7x8_o30-hXpdog  0.581940  -1.954490
Ahwatukee  qdCwzhJ5Yo_Sdm_bYDIfOQ  0.581291  -1.954769
Ahwatukee  qJf61TR4Jq9Xph5RiXPS9A  0.581287  -1.954647
Ahwatukee  jEt8ed_Z2cJaBNpLG1sfsw  0.582031  -1.954385
Ahwatukee  gPK7baX7rd5JVvgytywRmw  0.581273  -1.954681
Ahwatukee  fidQ0oNwETh2LEGDZdfA7w  0.581545  -1.954612
Ahwatukee  eggiaEDKJqrrHlDZqlOSow  0.581552  -1.954367
Ahwatukee  ko9g03dv34Ftz37Q6J5C9Q  0.581502  -1.954437
Ahwatukee  aNBjTE6FK1XrgssMq-BO4g  0.581284  -1.954612
Ahwatukee  ZzZO_FIzICDLxHs7ooYgbQ  0.581409  -1.955397
Ahwatukee  UY1BHeeb1oE0-uk0EKqaGg  0.582043  -1.954332
Ahwatukee  FYWN1wneV18bWNgQjJ2GNg  0.581730  -1.954402
Ahwatukee  ALvsc69ygqJfG5wLRryj-g  0.581940  -1.954490
Ahwatukee  0Rni7ocMC_Lg2UH0lDeKMQ  0.581511  -1.954490
Ahwatukee  -v8Z3mdbbPs1ljLziHr2DA  0.581783  -1.954385
Ahwatukee  eVv6cnwhabK8ig5Di2hXQQ  0.581488  -1.954839